### ISSUE TITLE
3_CLAS stage classifies biasCor instead of SIMDATA ??

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#131]
please check $PIPPIN_OUTPUT/KVA23_ANA_CALIBSHIFTS/3_CLAS/SNNTESTV19_z_5_DES_SIMDATA_Baseline_SNNTRAINV19_z_TRAINDES_V19
and note that job.slurm points to BIASCOR instead of SIMDATA ... and predictions.csv has 1.1 million events instead of ~2000.

**Comment by OmegaLambda1998** [comment]
In this commit (b8d5669) I removed what I believed to be an extraneous deepcopy which was significantly slowing down config creation, especially for large inputs with lots of biascors. Rather than removing it, we needed to turn it into a copy which allowed for multiple sims and biascors to share the same classification without slowing down everything. That's now been fixed
