### ISSUE TITLE
Pippin job status still shows 'running', but job finished succesfully 

### ISSUE THREAD

**Issue by am610** [dessn/Pippin#151]
Please look in this directory :
`/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU`

the stage `6_BIASCOR` finished successfully (check `MERGE.LOG`) but the job died, and Pippin status still shows grey.

**Comment by OmegaLambda1998** [comment]
When you say "the job died" do you mean the BBC job, the sbatch job, or the Pippin job?

If you copy the hash.txt to a temporary file, cancel the pippin job, and then bring the hash.txt back Pippin should recognise that the job finished and move on.

**Comment by am610** [comment]
the `sbatch` job died, so there is no requirement of cancelling the pippin job.  Nothing in the queue. So I can move the `hash.txt` to a backup file and reran `pippin` ? Maybe it will try to create a new hash file and in the process notice the status (which is completed) and make the stage 6 green ?

<img width="1075" alt="Screenshot 2023-10-18 at 09 57 10" src="https://github.com/dessn/Pippin/assets/6508278/b946aff4-5943-4b36-b662-39296a4966b1">

**Comment by OmegaLambda1998** [comment]
So you're going to have to cancel the pippin job in order to rerun Pippin (otherwise you might get some weird conflicts)

1. Copy the hash files inside $PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/6_BIASCOR to temporary files, probably best to save them outside 6_biascor so it doesn't get removed
2. Cancel the Pippin job. When you cancel a job, Pippin treats this as the job erroring. This is to stop situations in which a job is half finished and errored, which means Pippin doesn't know what to do
3. Replace hash.txt with the copied version. This tricks Pippin into thinking it already ran the job, so it should just check if the job finished
4. Rerun pippin. You should see the job turn green.

**Comment by am610** [comment]
How do I cancel the pippin job ? everything is already dead. After 3 days. Only the pippin status is showing white for stage 6. Nothing is running in the background.

**Comment by OmegaLambda1998** [comment]
If Pippin is open in a screen or terminal or some, ctrl cos all you need. If the white is just in pippin status file then that's just what the most recent status was.

Use ctrl c to cancel whatever pippin job you have running and then rerun pippin?

**Comment by am610** [comment]
Yeah, ok so I will just rerun pippin. Will report back.

**Comment by am610** [comment]
I started, and I see that the `MERGE.LOG` file went completely to "`WAIT`" for all entries. I was hoping that pippin will read the "`DONE`" status of the `MERGE.LOG` file and not rerun them again, but it seems it will do that again.

**Comment by OmegaLambda1998** [comment]
Did you do the thing with the hash files?

If so I'll check the logs to see what happened.

**Comment by OmegaLambda1998** [comment]
@am610 What's the status of this issue?

**Comment by am610** [comment]
Closing it.
