### ISSUE TITLE
strange characters in wfit input file created by Pippin

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#84]
I just noticed that Pippin produces

  WFITOPT: &id001   
  - /CMB_PRI/  -cmb_sim -sigma_Rcmb 0.007
  - /CMB_PRI+BAO/  -cmb_sim -sigma_Rcmb 0.007 -bao_sim
  - /Wa+CMB/ -wa -wasteps 101 -w0steps 101 -cmb_sim -sigma_Rcmb 0.007
  - /Wa+CMB+BAO/ -wa -wasteps 101 -w0steps 101 -cmb_sim -sigma_Rcmb 0.007 -bao_sim
  - /SN-ONLY/ -ompri 0.315 -dompri 0.9
  WFITOPTS: *id001

The '&id001' is garbage that I worry might eventually impact submit_batch. The WFITOPTS key is not used and will only cause confusion. It would help if the pippin input accepts either WFITOPT or WFITOPTS key and maps them both onto WFITOPT for submit_batch,

**Comment by OmegaLambda1998** [comment]
So those symbols are yaml anchors. It's basically telling yaml to copy everything after &id001 and paste it to *id001. Why it's doing that, I'm not sure - maybe an optimisation in python's yaml package. I agree that clobbering WFITOPTS into WFITOPT is the solution though, I'll get that working soon.

**Comment by OmegaLambda1998** [comment]
Yup, when using yaml.safe_dump if you have two keys referencing the same python object (i.e an object with the same id) then yaml will make use of anchors rather than writing out the same object twice. This means when loading in, those two keys will write to the same object id as well, so you can have consistent behaviour.

This will go away when removing the WFITOPTS key

**Comment by OmegaLambda1998** [comment]
This change has been pushed with commit fb9c1fa. Just waiting for confirmation that it works now

**Comment by OmegaLambda1998** [comment]
Confirmed resolved
